#!/bin/sh

docker-compose down

mkcert -cert-file ./docker/ssl/auth.ms.pem -key-file ./docker/ssl/auth.ms.key auth.ms

docker-compose up -d --build --force-recreate

# Installing composer package `unlu/laravel-api-query-builder` fix
if ! eval "docker exec -it qw-auth-ms-php composer install"; then
  docker exec -it qw-auth-ms-php composer install
fi;
docker exec -it qw-auth-ms-php php bin/console migrations:migrate
docker exec -it qw-auth-ms-php php bin/console fixtures:load -t
